# Generated by Django 4.2.3 on 2023-08-01 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SatelliteData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "altitude",
                    models.DecimalField(
                        decimal_places=15, help_text="Satellite's altitude in kilometers", max_digits=30
                    ),
                ),
                ("last_updated", models.DateTimeField(help_text="Last recorded date from the satellite's data in UTC")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.localtime)),
            ],
        ),
    ]
