# Generated by Django 4.2.3 on 2023-08-02 00:00

from django.db import migrations


def add_interval_periodic_10_secs():
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(add_interval_periodic_10_secs),
    ]
